services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    environment:
      NODE_ENV: development

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.nuxt
    environment:
      NODE_ENV: development
      API_URL: http://api:3001
